### ISSUE TITLE
Converting CPU temperature from celsius to fahrenheit

### ISSUE THREAD

**Issue by DeadlyGentleman** [roele/istats.widget#10]
I am trying to write the code to display the CPU in Fahrenheit rather than Celsius but i can't seem to get it right, everything I have tried has broken the script. All help will be appreciated

**Comment by roele** [comment]
The formula to get from F to C is basically `T(°F) = T(°C) × 9/5 + 32`. 

Adding an option flag and a statement before https://github.com/roele/istats.widget/blob/master/istats.widget/index.js#L99 should do the trick. Something like 
```
if (this.ui.tempUnit === 'F') {
   data.cpu['cpu-temp'] = data.cpu['cpu-temp'] * 1.8 +32;
}
```
