### ISSUE TITLE
Widget Doesn't Display Correct Battery Level

### ISSUE THREAD

**Issue by DinoAlbatross** [roele/istats.widget#14]
Hi there, 
So I recently downloaded and installed the iStats widget, and I've noticed that the battery level tends to be off by 5% or so. Not sure if I should be that bothered about this, but I'd just rather not have to check my (auto-hide) menu bar every time I want to see my battery level if possible.

Any help would be appreciated.

-DA

**Comment by roele** [comment]
This is indeed a bug caused by the fact that the current percentage is calculated by `current-charge / maximum-charge * 100`. The maximum charge is not reached as battery ages so the parser should also make the percentages available for use for the battery stats.
