### ISSUE TITLE
Doesn't work on Mojave (10.14 final release)

### ISSUE THREAD

**Issue by GentleHoneyLover** [roele/istats.widget#16]
Hi,

Thx for the great widget! Have been using it for quite some time on High Sierra. With an upgrade to Mojave, the widget stoped rendering and now displays the output of istats command rather than dials themselves. The other Übersicht widgets I use work correctly.

Can you please help fix the issue?

The following is displayed on the desktop:

> --- CPU Stats ---
> CPU temp:               52.81°C     [32m▁[0m[32m▂[0m[93m▃[0m[93m▅[0m▆▇
> 
> --- Fan Stats ---
> Total fans in system:   2           
> Fan 0 speed:            2285 RPM    [32m▁[0m[32m▂[0m▃▅▆▇
> Fan 1 speed:            2104 RPM    [32m▁[0m[32m▂[0m▃▅▆▇
> 
> --- Battery Stats ---
> Battery health:         Good        
> Cycle count:            80          [32m▁[0m[32m▂[0m▃▅▆▇  8.0%
> Max cycles:             1000        
> Current charge:         6365 mAh    [32m▁[0m[32m▂[0m[32m▃[0m[32m▅[0m[32m▆[0m[32m▇[0m  100%
> Maximum charge:         6421 mAh    [32m▁[0m[32m▂[0m[32m▃[0m[32m▅[0m[32m▆[0m[32m▇[0m  96.3%
> Design capacity:        6669 mAh    
> Battery temp:           33.3°C      
> 
> --- Extra Stats ---
> TG0D GPU 0 Die temp:    57.81°C     [32m▁[0m[32m▂[0m[93m▃[0m[93m▅[0m▆▇

**Comment by roele** [comment]
Please try the following in your terminal.
* re-install the XCode Command Line Tools via `xcode-select --install` 
* re-install iStats via `sudo gem install iStats`
* verify iStats is working via `iStats`
* refresh all widgets or restart Übersicht

**Comment by GentleHoneyLover** [comment]
I found a solution. The first line of the `istats` output was:

> Ignoring iStats-1.5.2 because its extensions are not built.  Try: gem pristine iStats --version 1.5.2

then I ran 

> $ sudo gem pristine iStats --version 1.5.2
> Restoring gems to pristine condition...
> Building native extensions.  This could take a while...
> Restored iStats-1.5.2

And now the widget renders correctly.
