### ISSUE TITLE
istat not working on mojave

### ISSUE THREAD

**Issue by metatron23** [roele/istats.widget#17]
When upgrading to Mojave the widget is not working anymore (you see the same data as in terminal, no UI)
<img width="565" alt="screenshot 2018-09-30 at 15 30 11" src="https://user-images.githubusercontent.com/10022028/46258146-ce16c400-c4c5-11e8-8390-b952be241e5b.png">

**Comment by roele** [comment]
Please see #16 for possible resolutions.
