### ISSUE TITLE
Icons not showing up...

### ISSUE THREAD

**Issue by MaybeCarter** [roele/istats.widget#20]
Everything seems to be working fine, except that the icons within the donuts don't show up. I think I did everything correctly. See attached screenshot for reference. Any help is appreciated. thanks in advance! 
<img width="313" alt="Screen Shot 2019-04-21 at 3 56 49 PM" src="https://user-images.githubusercontent.com/37084442/56474875-14c21080-644e-11e9-9699-e3eee1384e0c.png">

**Comment by roele** [comment]
It looks like the custom icon font `icons.ttf` is not loaded properly. In the file `index.js` the style section defines a `@font-face` with a hardcoded path. If you renamed the extracted folder, Übersicht might not be able to load the font.

**Comment by MaybeCarter** [comment]
I don't think that's the issue... to the best of my knowledge, I haven't renamed anything. I re-downloaded the widget to be sure, and the issue persists. 

<img width="747" alt="Screen Shot 2019-04-24 at 1 17 59 AM" src="https://user-images.githubusercontent.com/37084442/56634204-20206200-662f-11e9-8b5b-cc57e8b1d478.png">
<img width="215" alt="Screen Shot 2019-04-24 at 1 19 14 AM" src="https://user-images.githubusercontent.com/37084442/56634214-26164300-662f-11e9-8e54-3be75d6f2d6c.png">

Here are screenshots of the `icon.ttf` file and the directory structure. Let me know if I need to make any changes to make it work. Thanks so much!

**Comment by roele** [comment]
To what directory does your `Widgets Folder` preference of Übersicht point to? Usually this is pointing to a `widgets` folder which contains multiple widgets. I assume it's pointing directly to the `istats.widget` folder instead which renders the `@font-face` declaration invalid as it contains the folder path.

**Comment by MaybeCarter** [comment]
*Perfect!* That was the issue! I moved both files up one level and the icons appeared. Thank you so much for the help- I love the widget.
