### ISSUE TITLE
Spinning animation not updated

### ISSUE THREAD

**Issue by etrahretep** [roele/istats.widget#21]
Spinning animation not updated on High Sierra and Mojave.
Circle is updated, spinning animation not.

**Comment by roele** [comment]
You mean the speed of the spinning animation is not updated or the animation is not enabled once set to `true`?. 
Please note that updates are tied to the `refreshFrequency` which is set to `5000ms` by default.

**Comment by etrahretep** [comment]
The fans spin. (40% on my MBP) spinning rate will only change when I manually refresh Ubersicht. refreshFrequency doesn't matter. Even after half an hour spinning isn't changed. As I said the battery and circle update but not the spinning fans. No matter the amount of ms. Tried from 100 to 10000 ms. Checking with Macs Fan Control; max out fan-speed; circle increases, spinning animations don't

**Comment by roele** [comment]
Seems to be an issue with the `animation` property as indicated by https://developer.mozilla.org/en-US/docs/Web/CSS/CSS_Animations/Tips#Run_an_animation_again

**Comment by etrahretep** [comment]
OK. fixable?

**Comment by etrahretep** [comment]
That still doesn't do the trick on my side...

**Comment by roele** [comment]
@etrahretep Pushed another commit which adds an additional class name which is required for resetting the animation and added a slight optimisation to deal with ugly flickering when spinning speed is slow.
