### ISSUE TITLE
Add ordering support for stats

### ISSUE THREAD

**Issue by etrahretep** [roele/istats.widget#22]
I managed to add extra (GPU) to the list. Is there an easy way to change the order of icons.
I'd like the GPU in second place...
Any help appreciated!

**Comment by roele** [comment]
I'd love to add GPU support by default, a pull request around this would be highly appreciated. For ordering there is currently no support yet but certainly a feature i would also love to add.

A starting point would be the [renderStats](https://github.com/roele/istats.widget/blob/master/index.jsx#L175) where the single stats are rendered by iterating over the keys of the data object via `Object.keys(data).map(key => {})`.

**Comment by etrahretep** [comment]
The easy way; these are the chances I made: 

(First off, enable stats key FG0D)

**index.css**

.icon-gpu:before {content: '\f108';}

**Transformer.js**

const handleGPUs = (input, output, key) => {
    output['extra'] = {
        'tg0d-gpu-0-die-temp': []
    };
    output['extra']['tg0d-gpu-0-die-temp'].push(input[key]['tg0d-gpu-0-die-temp']);
}
.
.
.
.
    if (key === 'extra') {
        handleGPUs(input, output, key);
        return true;

**index.jsx**

const getIcon = (data, key) => {
    if (key === 'cpu') {
        return 'icon-cpu';
    } else if (key === 'extra') {
        return 'icon-gpu';
.
.
.
const getPercentage = (data, key) => {
    if (key === 'cpu') {
        return Math.floor(data[key]['cpu-temp'][0] / MAX_CPU_TEMP * 100);
    } else if (key === 'extra') {
        return Math.floor(data[key]['tg0d-gpu-0-die-temp'][0] / MAX_CPU_TEMP * 100);
.
.
.
const getValue = (data, key) => {
    if (key === 'cpu') {
        return (cfg.tempUnit === 'F')
            ? Math.floor(data[key]['cpu-temp'][0] * 1.8 + 32) + '°F'
            : data[key]['cpu-temp'][0] + '°C';
    } else if (key === 'extra') {
        return (cfg.tempUnit === 'F')
            ? Math.floor(data[key]['tg0d-gpu-0-die-temp'][0] * 1.8 + 32) + '°F'
            : data[key]['tg0d-gpu-0-die-temp'][0] + '°C';
.
.
.


I suppose renderstats collects the order of /usr/local/bin/istats
