### ISSUE TITLE
Add support for extra stats

### ISSUE THREAD

**Issue by roele** [roele/istats.widget#23]
Add support for showing GPU temperature. 

According to [VirutalSMC](https://github.com/acidanthera/VirtualSMC/blob/master/Docs/SMCKeys.txt) the GPU temperature is available with SMC key `TCGC`. By the comment in #22 i assume that this key can vary from hardware to hardware and possibly should be made configurable.

**Comment by etrahretep** [comment]
Great, you may want to add an extra  'fan.fan-2-speed'  to index.jsx for there are machines with 3 fans...
Otherwise excellent enhancements!
