### ISSUE TITLE
there is an error in the web inspector and i can't add any cfg in the index.jsx cuz it's in no use

### ISSUE THREAD

**Issue by aws0me** [roele/istats.widget#25]
Warning: Each child in an array or iterator should have a unique "key" prop.

Check the top-level render call using <div>. See https://fb.me/react-warning-keys for more information.
    in div

**Comment by roele** [comment]
Can you confirm the version (e.g. 2.0.0) you're using and elaborate on the issues with the configuration?

**Comment by roele** [comment]
I'm unable to reproduce this issue with not further information, hence closing.
