### ISSUE TITLE
No animations and displaying weird

### ISSUE THREAD

**Issue by jaredbm** [roele/istats.widget#31]
![Screen Shot 2019-09-20 at 1 10 50 PM](https://user-images.githubusercontent.com/54719634/65345374-1d0eab00-dba8-11e9-8951-c96c720528c1.jpg)

**Comment by roele** [comment]
Looks like a CSS issue similar to #20.

**Comment by jaredbm** [comment]
Somehow the folder got saved with a 2 at the end so the directory was off for animations. That's fixed it, thanks!
