### ISSUE TITLE
Widget broken in macOS Catalina

### ISSUE THREAD

**Issue by jaredbm** [roele/istats.widget#33]
![Screen Shot 2019-10-08 at 12 29 57 PM](https://user-images.githubusercontent.com/54719634/66414401-5c6e3180-e9c7-11e9-8b53-38e8b5f9cc1d.jpg)

**Comment by etrahretep** [comment]
Been seeing that too since I installed AdGuard. Switching AdGuard on and off and refreshing widgets helps for now. No idea really if AsGuard is related however....

**Comment by roele** [comment]
Recent macOS upgrades showed similar issues as the upgrade seem to mess with Ruby and the installed Gems. Does the `istats` command work in the terminal? If not, i suggest you try to re-install the Ruby gem as indicated in the README.md (you might need to uninstall first).
If the `istats` command runs as expected, it's most likely a deeper issue related to WebKit which needs to be addressed at Ubersicht level.

**Comment by jaredbm** [comment]
@roele Reinstalling the gems fixed the issue for me. Thank you!
