### ISSUE TITLE
how to enable GPU for iMac

### ISSUE THREAD

**Issue by metatron23** [roele/istats.widget#37]
How to enable GPU temp for iMac? in istats gpu temp is shown as TG0D (GPU 0 Die), TG1D (GPU 1 Die), TG0P (proximity). iMac has Radeon Pro Vega graphic card-
The line in index.jsx 'extra.tcgc-peci-gpu-temp' is meant for intel gpu in mbp right?

**Comment by roele** [comment]
Once the key is enabled in istats, the value can be derived from istats output by using lower case and replacing spaces with a dash. So `TG0P GPU 0 Proximity` will translate to key value `extra.tg0p-gpu-0-proximity`.

**Comment by metatron23** [comment]
I have tried like this (see screenshot) but it is not shown in widget. What am I doing wrong?
![Screenshot 2019-10-21 at 17 31 33](https://user-images.githubusercontent.com/10022028/67219721-cacfdc80-f428-11e9-8b4a-014946630192.png)

**Comment by roele** [comment]
This looks correct. 

Is the istats key enabled properly? Respectively does the command `istats` also show the expected value for the key?
:warning: Note that an `istats scan` might reset the enabled keys.

Did you restart Übersicht after the change? There might be some caching/loading issues and changes to the config might only be shown after a hard restart.

**Comment by metatron23** [comment]
I have enabled all keys and also restarted Übersicht. istats show all keys, but in widget there are only 2 (cpu, fan). Strange

**Comment by roele** [comment]
Can you please attach the output of `istats > istats.txt`, maybe you're hitting a (parser) bug or similar.

**Comment by metatron23** [comment]
now my terminal doesn't work anymore (got this problem with "zsh: command not found: $"
trying to fix this, but it's not working (trying this solution https://stackoverflow.com/questions/18428374/commands-not-found-on-zsh

**Comment by roele** [comment]
Sorry, removed the `$` sign as i usually use this to indicate CLI commands...

**Comment by metatron23** [comment]
[istats.txt](https://github.com/roele/istats.widget/files/3752465/istats.txt)

**Comment by roele** [comment]
Okey thanks. Parser does not seem to have any issues with your output but it slightly differs from the attached screenshot in the sense that the keys end with ` temp:` and with that the key would become `extra.tg0d-gpu-0-die-temp`, `extra.tg0p-gpu-0-proximity-temp` or `extra.tg1d-gpu-1-die-temp`.

So basically the pattern is `<section>.<key>` where `<section>` is lower case of `--- <section> Stats ---` and `<key>` is lower case and spaces replaced by dash of `TG0D GPU 0 Die temp`.

**Comment by metatron23** [comment]
That worked! 
But now I have "new" problem, icons are not visible (I still have the non updated widget where icons are visible, but I can't add graphic ones). Any idea why?

p.s.
somehow I can't upload screenshot, tried several times :(

**Comment by roele** [comment]
Maybe the same issue as #20?

**Comment by metatron23** [comment]
icons.ttf and index.css are in the same folder as index.jsx (this should be like this no?)

**Comment by metatron23** [comment]
same structure as in old widget but there icons are visible

**Comment by metatron23** [comment]
https://d.pr/i/sth1Ic

**Comment by roele** [comment]
what does "old widget" mean? the include of the `index.css` is hardcoded (in `src/components/Stats.jsx`) with `istats.widget/index.css` so having a copy of the folder with another name will lead to non-properly rendered stats.

**Comment by metatron23** [comment]
I have 2 widget (so I can test new, updated one). one is called istat.widget, other one istat.widget 1
could this be the problem?

**Comment by roele** [comment]
If you use keys which do not contain `battery`, `cpu`, `gpu` or `fan` you might define a custom icon as described in the README.md.

**Comment by metatron23** [comment]
I have the widgets displayed, but without icons. Damn :)
![Screenshot 2019-10-23 at 17 31 33](https://user-images.githubusercontent.com/10022028/67409558-06021500-f5bb-11e9-938c-dc768591d175.png)

**Comment by roele** [comment]
Only thing i can recommend at this point is to use the Übersicht `Show Debug Console` and try to figure out why the icons are not rendered.

<img width="1247" alt="Screenshot 2019-10-23 at 18 59 50" src="https://user-images.githubusercontent.com/181773/67416654-7dd63c80-f5c7-11e9-92eb-2a33869ec4f3.png">

**Comment by metatron23** [comment]
Strangely enough after I had removed all widgets and reinstalled them all, everything works now. It seems that there was something wrong when I added twice same widget (old and updated version).

Thank you again @roele for all the help!
