### ISSUE TITLE
Mojave Error in Place of Widget

### ISSUE THREAD

**Issue by MrGVSV** [roele/istats.widget#39]
I followed the instructions to install the widget properly but an error is being shown in place of the widget.

```
Invariant Violation: Objects are not valid as a React child (found: Error: env: ruby_executable_hooks: No such file or directory
). If you meant to render a collection of children, use an array instead.
```

iStats works fine in the terminal and the `command` variable in `index.jsx` is pointing to my iStats binary. Not sure what's going wrong as I'm new to Übersicht and stuff.

System: Mac OSX Mojave 10.14.6
Ruby: ruby 2.5.1p57 (2018-03-29 revision 63029) [x86_64-darwin16]
Gem: ~/.rvm/rubies/ruby-2.5.1/bin/gem
iStats: /usr/local/bin/istats
Uber: v1.4

**Comment by roele** [comment]
I am assuming you are using the latest [istats.widget-2.2.0](https://github.com/roele/istats.widget/releases) with no modifications to the source?

To further pin down the issue a more explicit error description is required. Would you be able to open "Show Debug Console" from the Übersicht context menu and provide the output from the "Console" tab? I would expect a more detailed error description is shown in the Console with the file and line number where this error occurs exactly.

**Comment by MrGVSV** [comment]
It's actually iStats v1.6.1. And yes I have not modified it at all.

Do these screenshots from the console help at all?

![image](https://user-images.githubusercontent.com/49806985/71625387-65bd0380-2b9c-11ea-8b70-3e4cfdb56240.png)
![image](https://user-images.githubusercontent.com/49806985/71625392-6d7ca800-2b9c-11ea-8f8a-5bbb7185c8fa.png)

**Comment by roele** [comment]
Usually the error indicates the widget causing the problem.

<img width="853" alt="Screenshot 2020-01-01 at 13 32 29" src="https://user-images.githubusercontent.com/181773/71643700-6ab4ac80-2c9b-11ea-9802-2a0be714a733.png">

In your case it seems that the widget is not even loaded. Please check if your Übersicht preferences point to a directory containing the widget, rather than the widget itself. Also see #20 for other potential issues around widget folders.

**Comment by MrGVSV** [comment]
My preferences are pointing to the widgets folder and I'm able to load up other widgets. Do you think it has anything to do with `ruby_executable_hooks`? I just ran `sudo gem install --user-install executable-hooks` and it was successfully installed but didn't help. I'm not too familiar with ruby so maybe I'm missing something here.

**Comment by roele** [comment]
@MrGVSV Hard to tell what's going on here. To me this seems somehow related to your environment. Does the `istats` command run properly in your command line? Is the executable located/symlinked at `/usr/local/bin/istats` as indicated in the [script](https://github.com/roele/istats.widget/blob/master/index.jsx#L64)?

**Comment by drewswaycool** [comment]
I am having this issue as well. On Catalina and using the latest release of the widget.

**Comment by roele** [comment]
@drewswaycool How does your environment look like in terms of versions (macOS, Ruby, Gem, rvm)? Do you use `rvm` as well like @MrGVSV?

```
$ which istats && which ruby && which gem
/usr/local/bin/istats
/usr/bin/ruby
/usr/bin/gem
$ sw_vers -productVersion && ruby --version && gem --version && istats --version
10.15.3
ruby 2.6.3p62 (2019-04-16 revision 67580) [universal.x86_64-darwin19]
3.0.3
iStats v1.6.1
```

**Comment by drewswaycool** [comment]
```
$ which istats && which ruby && which gem
/Users/drew/.rvm/rubies/ruby-2.5.1/bin/istats
/Users/drew/.rvm/rubies/ruby-2.5.1/bin/ruby
/Users/drew/.rvm/rubies/ruby-2.5.1/bin/gem
$ sw_vers -productVersion && ruby --version && gem --version && istats --version
10.15.3
ruby 2.5.1p57 (2018-03-29 revision 63029) [x86_64-darwin18]
2.7.8
iStats v1.6.1
```

**Comment by roele** [comment]
@drewswaycool 
It seems you're also using [rvm](https://rvm.io) and the `istats` Gem is installed in this context. As `rvm` requires the script to be sourced in the `.bash_profile` i assume Übersicht it not executing the shell command with a properly initialized environment.

You could give the following options a try:
1. Enable `Load Bash env` in Übersicht preferences.
2. Edit the `command` constant in `index.jsx` to something like `source $HOME/.bash_profile && /usr/local/bin/istats`.

**Comment by drewswaycool** [comment]
Nice, just needed to turn `Load Bash env` and change the path to istats in the index.jsx. Thanks.

**Comment by roele** [comment]
Thanks for confirming @drewswaycool. I added a troubleshooting item to the README.md for RVM.
