### ISSUE TITLE
Breaks desktop

### ISSUE THREAD

**Issue by jaredbm** [roele/istats.widget#43]
It seems to be breaking my desktop all of a sudden where all icons become unclickable. If I disable this widget they become clickable again. I wasn't having this issue until recently.

**Comment by jaredbm** [comment]
I think I fixed it now with disabling interaction. Not sure why that was turned on all of a sudden. Maybe with a recent update

**Comment by roele** [comment]
Most probably an Übersicht issue (see [#424](https://github.com/felixhageloh/uebersicht/issues/424)) and not related to the widget. 

I'll check if something can be done from the widget side to prevent having to disable the interaction option in the  preferences.
