### ISSUE TITLE
Error when waking from sleep or login

### ISSUE THREAD

**Issue by etrahretep** [roele/istats.widget#44]
I get this error every time the Mac wakes from sleep or when I login.
Running the latest istats/ubersicht on Big Sur beta 8

Any remedy?

[Error] Failed to load resource: The network connection was lost. (run, line 0)
[Error] Failed to load resource: The network connection was lost. (run, line 0)
[Error] Failed to load resource: The network connection was lost. (run, line 0)
[Error] Invariant Violation: Objects are not valid as a React child (found: Error: error running command). If you meant to render a collection of children, use an array instead.
    in div
    in Error
	(anonymous function) (client.js:1:30533)
	throwOnInvalidObjectType (client.js:1:247380)
	(anonymous function) (client.js:1:262806)
	reconcileChildrenAtExpirationTime (client.js:1:270092)
	reconcileChildren (client.js:1:269871)
	(anonymous function) (client.js:1:288470)
	performUnitOfWork (client.js:1:334759)
	workLoop (client.js:1:335598)
	callCallback (client.js:1:37840)
	dispatchEvent
	invokeGuardedCallback (client.js:1:37927)
	invokeGuardedCallback (client.js:1:39026)
	replayUnitOfWork (client.js:1:344446)
	renderRoot (client.js:1:336674)
	performWorkOnRoot (client.js:1:351020)
	performWork (client.js:1:349356)
	performSyncWork (client.js:1:348268)
	requestWork (client.js:1:346645)
	scheduleWork$1 (client.js:1:342703)
	(anonymous function) (client.js:1:355658)
	(anonymous function) (client.js:1:364643)
	legacyRenderSubtreeIntoContainer (client.js:1:367460)
	render (client.js:1:769967)
	redraw (client.js:1:766132)
[Error] The above error occurred in the <div> component:
    in div
    in Error

Consider adding an error boundary to your tree to customize error handling behavior.
Visit https://fb.me/react-error-boundaries to learn more about error boundaries.
	(anonymous function) (client.js:1:303867)
	logError (client.js:1:303886)
	(anonymous function) (client.js:1:315140)
	callCallback (client.js:1:222115)
	commitUpdateQueue (client.js:1:223057)
	commitLifeCycles (client.js:1:306744)
	commitAllLifeCycles (client.js:1:324784)
	callCallback (client.js:1:37840)
	dispatchEvent
	invokeGuardedCallback (client.js:1:37927)
	invokeGuardedCallback (client.js:1:39026)
	commitRoot (client.js:1:328295)
	completeRoot (client.js:1:351512)
	performWorkOnRoot (client.js:1:351059)
	performWork (client.js:1:349356)
	performSyncWork (client.js:1:348268)
	requestWork (client.js:1:346645)
	scheduleWork$1 (client.js:1:342703)
	(anonymous function) (client.js:1:355658)
	(anonymous function) (client.js:1:364643)
	legacyRenderSubtreeIntoContainer (client.js:1:367460)
	render (client.js:1:769967)
	redraw (client.js:1:766132)
[Error] Failed to load resource: The network connection was lost. (run, line 0)
[Error] Failed to load resource: The network connection was lost. (run, line 0)

**Comment by roele** [comment]
@etrahretep Are you still seeing this issue? So far i was not able to see the mentioned issue or reproduce the error on my side.
