### ISSUE TITLE
Error keyword class

### ISSUE THREAD

**Issue by Tronbo** [roele/istats.widget#46]
The error that pops up on my desktop is 
<img width="501" alt="Screen Shot 2021-01-27 at 7 43 20 PM" src="https://user-images.githubusercontent.com/67758739/106073373-e91a9280-60d7-11eb-8883-c4949d7c6775.png">

I've tried the debugging methods but they didn't work. If you could help, that would be greatly appreciated!

Thank you!

**Comment by roele** [comment]
@Tronbo Not enough information to help you out. Could you please open the Übersicht Debugger (Show Debug Console) and paste the Console output when the error happens?
