### ISSUE TITLE
🔴 Objects are not valid as a React child

### ISSUE THREAD

**Issue by vivek-vijayan** [roele/istats.widget#49]
Getting error after installing

![Screenshot 2021-05-17 at 9 59 05 PM](https://user-images.githubusercontent.com/53655378/118523775-1a889e00-b75b-11eb-98e2-c5c60788cb32.png)

**Comment by roele** [comment]
Did you follow the instructions from the [prerequisites](https://github.com/roele/istats.widget#prerequisites) to install the `istats` binary? 

The Bash script expects the `istats` binary to be installed in `/usr/local/bin/istats` which seems to be missing.
What is the output for `which istats`?

**Comment by vivek-vijayan** [comment]
Great 🚀 ... that works !!! 🔥
