### ISSUE TITLE
istats.sh does not honor RVM environment

### ISSUE THREAD

**Issue by roele** [roele/istats.widget#6]
Under some circumstances the `istats.sh` does not honor the RVM environment propertly and the widget does not render anything as reported by @thesp0nge.

**Comment by roele** [comment]
@thesp0nge Would you mind sharing your exact setup? 
How did you install RVM? 
What version are you running? 
How did you install the Gem? 
Locations of the binaries `$(which ruby)` and `$(which istats)` etc. ?
Your ENV variable?

The `istats.sh` has been tested on a Yosemite vagrant box with RVM installed and it basically worked for me besides not showing any charts exept 0% CPU (Sensors are not reported in the VM).

**Comment by thesp0nge** [comment]
rvm 1.26.11 (master) by Wayne E. Seguin wayneeseguin@gmail.com, Michal Papis mpapis@gmail.com [https://rvm.io/]

rvm is installed in my home.
gem is installed via gem install iStats performed on rvm 2.2.2@global gemsets
/Users/thesp0nge/.rvm/rubies/ruby-2.2.2/bin/ruby
/Users/thesp0nge/.rvm/gems/ruby-2.2.2/bin/istats

**Comment by roele** [comment]
Thanks @thesp0nge, i am able to reproduce the issue on a Vagrant box. However i'm afraid that this is more an übersicht issue as RVM is installed in the user directory and referenced in the PATH variable. The shell which übersicht spawns does not seem to honour those environment variables properly.

The workaround i found so far would be to call `source ~/.bash_profile` in the `istats.sh` prior to execute the `istats` binary.

**Comment by thesp0nge** [comment]
Just cloned the changed shell script but nothing happened. Opening debug console shows nothing. Really weird. However, thanks for supporting
