### ISSUE TITLE
Nothing shows up 

### ISSUE THREAD

**Issue by rivetmichael** [roele/istats.widget#7]
Hi,

i can't get it working ! I install the gem istats, the bash script work but i see nothing in the ubersicht debug  console. No errors, but the XHR calls are empty.

Any ideas ?

**Comment by roele** [comment]
Can you please provide more information about your setup (OS/Ruby version, Env variables etc.)

**Comment by ulfmaier** [comment]
Same for me ... maybe it's the same problem, so i give some details.

The div of the widget is empty.
No errors in console.
Running the istats.sh script of the widget shows the stats as expected.
output variable in function parseOutput is empty.

Changing the command in the JS from the istats.sh to "/usr/local/bin/istats" made it working for me.

OS X 10.11.3 (newest release)
Übersicht 0.8 (newest release)
ruby 2.0.0p645
PATH=/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/opt/X11/bin:other unrelated stuff

**Comment by zebernst** [comment]
I was having the same issue with an empty div, but my problem was that I use `rbenv` to manage my ruby versions and gems. As such, `which istats` returned "~/.rbenv/shims/istats" instead of "/usr/local/bin/istats". I also use zsh as my shell, and sourcing my `.zshrc` file threw errors about the zsh-specific functions such as `autoload`, `zmodload`, etc. 

I found that adding 

``` bash
PATH=/usr/local/bin:$PATH
eval $(rbenv -init)
```

to the top of the "istats.sh" script before attempting to run the istats gem fixed the problem for me.

**Comment by roele** [comment]
@galaxyutii thanks for the heads-up. There seems to be indeed an issue with how übersicht spawns the shell (via node). Environment variables are not passed and therefore causes issues with certain setups.

**Comment by Gallost** [comment]
Same issue but I fixed it by simply deleting the #! before the file path in the istats.sh file. But does anyone know how to change the position of the things? I can't seem to figure it out.

Edit: nevermind I am stupid I figured it out.

**Comment by metatron23** [comment]
I tried all provided solutions, but I still can get it to work.
Could someone provide what needs to be done to make it work (on MacOS Sierra).

**Comment by codefromhezad** [comment]
@metatron23 : 
A bit late but I just stumbled on this page since I had the same issue. @ulfmaier 's solution worked perfectly for me. Just in case, here are the actions I did to make it work :

1) Edit `istats.sh` in the `istats.widget/` folder.
2) Replace both occurences of `iStats` with `/usr/local/bin/istats`
3) Refresh all widgets (In the übersicht menu)

(Nice work @roele by the way, thanks for the widget)

**Comment by metatron23** [comment]
thx @hezad for the instructions! that helped.
now I have to figure how to move it :) just changing vertical/horizontal position doesn't work (still looking in style part).

**Comment by MacCliF** [comment]
thx @hezad that worked for me two.
I need to figure how to include my GPU temp, I already had it on my istats extra.

EDITED: Succeded! img capture attached
![captura de pantalla 2017-05-08 a las 18 30 22](https://cloud.githubusercontent.com/assets/199715/25814191/dd4ace0c-341c-11e7-97ff-fb58585ed32a.png)

**Comment by Gunnthorian** [comment]
@MacCliF I have the TG0P GPU 0 Proximity enabled however how do you get the data? I guess my question is how to get the gpu temp, using istats extra I can get the temp in terminal. however data.extra is undefined, I'm clearly doing this wrong, how is it suppose to be done?

**Comment by MacCliF** [comment]
@Gunnthorian sorry for the longtime xD
I've been really busy learning other stuff, but now I'm ready to dive in Git and Github again, I've already visited your own fork with all the needed modifications to make the GPU temp up and running, and you added the screenshot and a custom set of icons, great Work!!
I'm really new to Git and I really didn't know back then how to contribute, making a fork, adding a pull request or anything about that.
My first fork is from your own iStats Fork I'm still learning
Keep coding simple!

**Comment by metatron23** [comment]
@MacCliF how did you manage to add GPU temp?

**Comment by Gunnthorian** [comment]
@metatron23 Feel free to snoop in my branch of istats.widget
[Gunnthorian/istats.widget](https://github.com/Gunnthorian/istats.widget)
Here is a snippet from my repository that should help out if you're trying to get GPU temp to work:
```
if (data.extra) {
  var temperature = (this.ui.unit.toUpperCase() === 'C')
    ? Math.floor(data.extra['tg0d-gpu-0-die-temp']) + '°C'
    : Math.floor(data.extra['tg0d-gpu-0-die-temp'] * 1.8 + 32) + '°F';
  
  $('#stats .gpu circle.bar').css('stroke-dasharray', Math.floor( (data.extra['tg0d-gpu-0-die-temp'] / MAX_CPU * 100) * c/100) + ' ' + c);
  $('#stats .gpu .temp').text(temperature);
}
```
You cannot simply use ```gpu-temp``` like you can for ```cpu-temp```, instead its ```tg0d-gpu-0-die-temp```. Atleast that was the case for me, just type ```istats``` into terminal and check what the gpu temp is called.

<img width="304" alt="screen shot 2018-01-29 at 9 09 09 am" src="https://user-images.githubusercontent.com/7622949/35514473-4e918bc2-04d4-11e8-88a8-7e0795af488c.png">

(above all make sure you've enabled GPU as an extra in istats ```istats enable TG0P```)

**Comment by metatron23** [comment]
![screen shot 2018-01-31 at 08 47 11](https://user-images.githubusercontent.com/10022028/35610896-69a5a14c-0663-11e8-9a08-f8a7df281a11.png)
thx! managed to add gpu temp :) somehow the icon for gpu doesn't work.

solved :)
![screen shot 2018-01-31 at 09 18 01](https://user-images.githubusercontent.com/10022028/35612064-a931ca9e-0667-11e8-809b-df4fa365e5b5.png)

**Comment by johngemach** [comment]
@metatron23 how did you make the icons show up? Mine don't show at all :-/
![bildschirmfoto 2018-02-09 um 01 30 29](https://user-images.githubusercontent.com/30899372/36005627-d47be432-0d38-11e8-8dae-6e9b2967e020.png)

**Comment by pavstor** [comment]
@MacCliF, can you please share your GPU icon?

**Comment by roele** [comment]
Given most of you resolved the issue by using the default installation path it might be better to keep the default location `/usr/local/bin/istats` with a comment in the code and README to adapt it in case rvm or rbenv are used.
