### ISSUE TITLE
OSX El Capitan

### ISSUE THREAD

**Issue by techassistant** [roele/istats.widget#8]
This doesn't work nothing shows up I'm new to Übersicht

**Comment by Metal-Snake** [comment]
works fine on El Capitan.

what happens when you enter

```
istats
```

 into the terminal?

**Comment by roele** [comment]
@techassistant This might be a known issue (#7). Did you try the workaround mentioned in #7 replacing the command?

I'd appreciate some more details about your setup (OS/Ruby version, Env variables etc.)

**Comment by techassistant** [comment]
When I type istats it shows me my CPU temp and fan speeds I tried issue #7 and it did not work  how do I find the ruby version and env variables sorry I am new to all of this.

**Comment by roele** [comment]
Closing as duplicate of #7
