### ISSUE TITLE
OSX Sierra Rotates circles 90º right

### ISSUE THREAD

**Issue by Jacobvs** [roele/istats.widget#9]
How do i fix/ counteract this? The widget still works but the "top" of the circles is now at 3 o'clock.

**Comment by roele** [comment]
@Jacobvs Looks like there is an issue with Safari (or whatever Ubersicht uses). If you change `#stats .chart svg` to `-89.9deg` it seems to look better even though the shown circle does not seem to be accurate (i.e. 50% taking more than half the circle)

**Comment by Jacobvs** [comment]
Thanks, it seems to work for now. Although the accuracy seems to be fine for me. I also added an option to toggle between Cº and Fº for the temperature which might be useful to add as well.

**Comment by roele** [comment]
@Jacobvs It seems to be definitively a Browser issue, the following example renders fine in Chrome but shows the exact same issue in Safari.

```
<doctype html>
<html>
    <head>
        <title>Untitled</title>
        <style type="text/css">
            body {
                font-family: 'Verdana';
                font-size: 0.825rem;
                color: #666;
            }
            .chart {
                position: relative;
                float: left;
                margin: 0rem 0rem 0rem 0rem;
            }
            .chart svg {
              transform: rotate(-90deg);
            }
            .chart circle {
              fill: transparent;
            }
        </style>
    </head>
    <body>
        <div class="chart">
            <svg width="74px" height="40px">';
                <circle class="bg" r="18" cx="37" cy="20" style="stroke: #ccc; stroke-width: 2; stroke-dasharray: 113.094 113.094"/>';
                <circle class="bar" r="18" cx="37" cy="20" style="stroke: #666 ; stroke-width: 2; stroke-dasharray: 56.547 113.094" />';
            </svg>
        </div>
    </body>
</html>
```
